# Generated by Django 2.2.11 on 2020-03-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='users',
            name='picture',
            field=models.FileField(null=True, upload_to='pic_images/'),
        ),
        migrations.AddField(
            model_name='users',
            name='us_phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
