# Generated by Django 2.2.11 on 2020-03-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0002_auto_20200320_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_edit_date',
            new_name='updated_at',
        ),
    ]
