# Generated by Django 2.2.11 on 2020-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0003_auto_20200320_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='usertype',
            field=models.BooleanField(default=True),
        ),
    ]
