# Generated by Django 2.1 on 2020-03-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0003_auto_20200320_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
