# Generated by Django 2.1 on 2020-03-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0004_users_email_confirmed'),
        ('users_auth', '0004_users_usertype'),
    ]

    operations = [
    ]
