# Generated by Django 2.1 on 2020-03-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0006_users_re_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='us_phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
