# Generated by Django 2.1.15 on 2020-04-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0009_auto_20200402_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
