# Generated by Django 2.1.15 on 2020-04-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0010_auto_20200402_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
