# Generated by Django 2.2.11 on 2020-04-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0011_users_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
