# Generated by Django 2.2.11 on 2020-04-03 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0013_auto_20200403_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(blank=True, upload_to='users', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
