# Generated by Django 2.2.11 on 2020-04-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0014_auto_20200403_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(blank=True, upload_to='users'),
        ),
    ]
