# Generated by Django 2.2.11 on 2020-03-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_projects_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_pics',
            name='prj_pic',
        ),
    ]
