# Generated by Django 2.2.11 on 2020-03-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20200318_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
