# Generated by Django 2.2.11 on 2020-03-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_project_user_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='totaltaget',
            new_name='totaltarget',
        ),
    ]
