# Generated by Django 2.2.11 on 2020-03-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_auto_20200321_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='updated_at',
        ),
    ]
