# Generated by Django 2.2.11 on 2020-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_remove_projects_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
