# Generated by Django 2.2.11 on 2020-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_project_pics_prj_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Project_tags',
        ),
    ]
