# Generated by Django 2.2.11 on 2020-03-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0015_project_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
