# Generated by Django 2.2.11 on 2020-03-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0003_auto_20200320_1333'),
        ('Project', '0016_projects_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_User_Comment_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=0)),
                ('dislike', models.BooleanField(default=0)),
                ('reports', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scomment', to='Project.Project_comments')),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sproject', to='Project.Projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suser', to='users_auth.Users')),
            ],
        ),
    ]
