# Generated by Django 2.2.11 on 2020-03-26 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0003_auto_20200320_1333'),
        ('Project', '0017_project_user_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_user_comment_post',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='reports',
        ),
        migrations.CreateModel(
            name='Project_User_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rproject', to='Project.Projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruser', to='users_auth.Users')),
            ],
        ),
    ]
