# Generated by Django 2.2.11 on 2020-03-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0020_auto_20200327_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_comments',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='project_comments',
            name='likes',
        ),
    ]
