# Generated by Django 2.2.11 on 2020-03-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0021_auto_20200327_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_comments',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
