# Generated by Django 2.2.11 on 2020-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0022_auto_20200327_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_comments',
            name='title',
            field=models.CharField(default='----', max_length=100),
        ),
    ]
