# Generated by Django 2.1.15 on 2020-03-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0023_auto_20200327_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
